{
  "name": "${projectName}",
  "version": "${projectVersion}",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "lint": "eslint src/ --ext .ts,.vue --fix"
  },
  "dependencies": {
    "@element-plus/icons-vue": "2.3.1",
    "@vueuse/core": "^9.1.1",
    "axios": "1.8.2",
    "dayjs": "^1.11.15",
    "element-plus": "2.9.3",
    "nprogress": "^0.2.0",
    "pinia": "^3.0.3",
    "pinia-plugin-persistedstate": "^4.4.1",
    "qs": "6.10.3",
    "sortablejs": "^1.15.6",
    "vue": "^3.5.17",
    "vue-router": "4.2.5",
    "xe-utils": "^3.5.4"
  },
  "devDependencies": {
    "@babel/types": "7.24.0",
    "@types/node": "20.11.28",
    "@types/nprogress": "0.2.3",
    "@types/qs": "6.9.12",
    "@types/sortablejs": "1.15.8",
    "@typescript-eslint/eslint-plugin": "^8.40.0",
    "@typescript-eslint/parser": "^8.40.0",
    "@vitejs/plugin-vue": "5.0.5",
    "@vue/compiler-sfc": "3.4.30",
    "@vue/eslint-config-prettier": "9.0.0",
    "@vue/eslint-config-typescript": "13.0.0",
    "@vue/tsconfig": "0.5.1",
    "eslint": "8.57.0",
    "eslint-plugin-prettier": "^5.5.4",
    "eslint-plugin-unused-imports": "^4.2.0",
    "eslint-plugin-vue": "9.23.0",
    "prettier": "3.2.5",
    "sass": "1.72.0",
    "typescript": "5.4.2",
    "vite": "6.3.4",
    "vite-plugin-svg-icons": "2.0.1",
    "vite-plugin-vue-setup-extend": "0.4.0",
    "vue-eslint-parser": "^10.2.0",
    "vue-tsc": "2.0.22"
  },
  "keywords": [
    "vue",
    "vue3",
    "vuejs",
    "vite",
    "element-plus",
    "${projectName}"
  ],
  "license": "MIT"
}
